kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: appassessment
  namespace: 1test-tools
  labels:
    app: appassessment
    app.kubernetes.io/component: appassessment
    app.kubernetes.io/instance: appassessment
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          volumes:
            - name: report-out
              persistentVolumeClaim:
                claimName: output
          containers:
            - name: appassessment
              image: >-
                image-registry.openshift-image-registry.svc:5000/1test-tools/appassessment
              env:
                - name: TARGET_NAMESPACE
                  value: 1test-tools
              resources: {}
              volumeMounts:
                - name: report-out
                  mountPath: /output/
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
