kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view
  namespace: 1test-tools
subjects:
  - kind: ServiceAccount
    name: app-assess
    namespace: 1test-tools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view

